version: 2

models:
  - name: stg_clients
    description: "Modèle de staging pour nettoyer les données clients."
    columns:
      - name: id_client
        description: "Identifiant unique du client."
        tests:
          - not_null
          - unique
      - name: email_client
        description: "Adresse e-mail du client, utilisée pour la communication."
        tests:
          - not_null

  - name: stg_vehicules
    description: "Modèle de staging pour nettoyer les données véhicules."
    columns:
      - name: id_vehicule
        description: "Identifiant unique du véhicule."
        tests:
          - not_null
          - unique
      - name: immatriculation
        description: "Numéro d'immatriculation du véhicule."
        tests:
          - not_null